#!/usr/bin/env python3
##
## EPITECH PROJECT, 2025
## Zappy
## File description:
## AiConnection
##

import socket

class Client:
    def __init__(self, host, port):
        self.host = host
        self.port = port
        self.sock = None

    def connect(self):
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.sock.connect((self.host, self.port))
        print("Connected to " + str(self.host) + ' ' + str(self.port))

    def send_command(self, command):
        if self.sock:
            self.sock.sendall(command.encode() + '\n'.encode())
            return self.sock.recv(4096).decode()
        else:
            raise ConnectionError("Not connected to server")

    def close(self):
        if self.sock:
            self.sock.close()
            print("Connection closed")




client = Client("zappy.antoiix.me", 12345)
client.connect()

try:
    while True:
        command = input("Enter command (or 'exit' to quit): ")
        if command == "exit":
            break
        response = client.send_command(command)
        print("Server response:", response)
finally:
    client.close()