#!/usr/bin/env python3
##
## EPITECH PROJECT, 2025
## Zappy
## File description:
## AiConnection
##

import socket

class Client:
    def __init__(self, host, port):
        self.__host = host
        self.__port = port
        self.__sock = None

    def connect(self):
        self.__sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.__sock.connect((self.__host, self.__port))
        print("Connected to " + str(self.__host) + ' ' + str(self.__port))

    def send_command(self, command):
        if self.__sock:
            self.__sock.sendall(command.encode() + '\n'.encode())
            return self.__sock.recv(4096).decode()
        else:
            raise ConnectionError("Not connected to server")

    def close(self):
        if self.__sock:
            self.__sock.close()
            print("Connection closed")




client = Client("zappy.antoiix.me", 12345)
client.connect()

try:
    while True:
        command = input("Enter command (or 'exit' to quit): ")
        if command == "exit":
            break
        response = client.send_command(command)
        print("Server response:", response)
finally:
    client.close()